# Generated by Django 6.1.1 on 2026-09-20 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('TIC_TAC_TOE', 'Tic Tac Toe'), ('BINGO', 'Bingo')], max_length=30)),
                ('mode', models.CharField(choices=[('PVP', 'Player vs Player'), ('PVC', 'Player vs Computer')], max_length=10)),
                ('current_turn', models.CharField(choices=[('P1', 'Player 1'), ('P2', 'Player 2')], default='P1', max_length=2)),
                ('state', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('DRAW', 'Draw')], default='WAITING', max_length=20)),
                ('winner_is_computer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
